### ISSUE TITLE
Crash on pageload

### ISSUE THREAD

**Issue by stephenthoma** [juhamust/mozaik-ext-slack#1]
With a stock mozaik dashboard of mozaik-demo getting a crash as soon as the page is loaded.

```
$ node app.js
info: registered API 'mozaik' (mode: poll)
info: registered API 'slack' (mode: poll)
info: serving static contents from /Users/stephenthoma/code/mozaik-demo/build
info: Mozaïk server listening at http://0.0.0.0:5000
info: Loaded slack 32 channels
info: Loaded 146 slack users
info: Started listening Slack events
info: Client #1 connected
info: Added subscription 'slack.message'
info: Calling 'slack.message'
/Users/stephenthoma/code/mozaik-demo/node_modules/mozaik/src/Bus.js:132
        callFn(params).then(function (data) {
                      ^

TypeError: Cannot read property 'then' of undefined
    at processApiCall (Bus.js:118:9)
    at Object.clientSubscription (Bus.js:189:17)
    at WebSocket.<anonymous> (server.js:53:24)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/stephenthoma/code/mozaik-demo/node_modules/mozaik/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/stephenthoma/code/mozaik-demo/node_modules/mozaik/node_modules/ws/lib/Receiver.js:536:18
    at /Users/stephenthoma/code/mozaik-demo/node_modules/mozaik/node_modules/ws/lib/Receiver.js:368:7
    at /Users/stephenthoma/code/mozaik-demo/node_modules/mozaik/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:639:5)
```

Config:

```
    slack: {
      token: process.env.SLACK_TOKEN,
      showImages: true,
      publicDir: './build',
      maxImageAge: '8 hours'
    },

.......

  dashboards: [
    {
      columns: 4,
      rows:    3,
      widgets: [
            {
          type: 'slack.pulse',
          channel: 'general',
          columns: 1, rows: 1,
          x: 1, y: 0
        }
      ]
    }
  ]
```

src/App.jsx

```
import React   from 'react';
import Mozaik  from 'mozaik/browser';
import slack   from 'mozaik-ext-slack';

const MozaikComponent = Mozaik.Component.Mozaik;
const ConfigActions = Mozaik.Actions.Config;

Mozaik.Registry.addExtensions({
  slack
});

React.render(<MozaikComponent/>, document.getElementById('mozaik'));

ConfigActions.loadConfig();
```

src/server.js:

```
import Mozaik  from 'mozaik';
import config  from '../config';
import slack   from 'mozaik-ext-slack/client';

const mozaik = new Mozaik(config);

mozaik.bus.registerApi('slack', slack);

mozaik.startServer();
```

**Comment by plouc** [comment]
It seems the extension does not returns a Promise, which is required.

**Comment by stephenthoma** [comment]
@plouc I think he intended to use push -- https://github.com/juhamust/mozaik-ext-slack/blob/master/src/client.js#L224, but it must be configured incorrectly?

**Comment by plouc** [comment]
@sthoma, I forgot this extension uses the push mode, so you misssed the third parameter:

``` javascript
mozaik.bus.registerApi('slack', slack, 'push');
```

**Comment by plouc** [comment]
@sthoma, it's on the README ;)

**Comment by stephenthoma** [comment]
Wow, that should have been obvious. Thanks @plouc! Sorry guys haha 😦

**Comment by plouc** [comment]
No problem :)

**Comment by juhamust** [comment]
Maybe I should always return a rejected promise with descriptive error msg - just to avoid the issue?

**Comment by plouc** [comment]
Good idea @juhamust, I think it should go in the doc (which should exist one day) about extensions authoring.
